#!/bin/bash
echo "--------- TASK 1 TESTS ---------"
echo "------------ Level 1 -----------"
echo "---> 1D_histo"
python m1_w2.py -t 1 -d 1D_hist -lvl 1 -src ../../Datasets/qsd2_w1 -store True

echo "---> 2D_histo, RGB, CH 0 & 1"
python m1_w2.py -t 1 -d 2D_hist -c RGB -ch1 0 -ch2 1 -lvl 1 -src ../../Datasets/qsd2_w1 -store True
echo "---> 2D_histo, RGB, CH 0 & 2"
python m1_w2.py -t 1 -d 2D_hist -c RGB -ch1 0 -ch2 2 -lvl 1 -src ../../Datasets/qsd2_w1 -store True
echo "---> 2D_histo, RGB, CH 1 & 2"
python m1_w2.py -t 1 -d 2D_hist -c RGB -ch1 1 -ch2 2 -lvl 1 -src ../../Datasets/qsd2_w1 -store True

echo "---> 2D_histo, HSV, CH 0 & 1"
python m1_w2.py -t 1 -d 2D_hist -c HSV -ch1 0 -ch2 1 -lvl 1 -src ../../Datasets/qsd2_w1 -store True
echo "---> 2D_histo, HSV, CH 0 & 2"
python m1_w2.py -t 1 -d 2D_hist -c HSV -ch1 0 -ch2 2 -lvl 1 -src ../../Datasets/qsd2_w1 -store True
echo "---> 2D_histo, HSV, CH 1 & 2"
python m1_w2.py -t 1 -d 2D_hist -c HSV -ch1 1 -ch2 2 -lvl 1 -src ../../Datasets/qsd2_w1 -store True

echo "---> 2D_histo, CieLAB, CH 0 & 1"
python m1_w2.py -t 1 -d 2D_hist -c CieLAB -ch1 0 -ch2 1 -lvl 1 -src ../../Datasets/qsd2_w1 -store True
echo "---> 2D_histo, CieLAB, CH 0 & 2"
python m1_w2.py -t 1 -d 2D_hist -c CieLAB -ch1 0 -ch2 2 -lvl 1 -src ../../Datasets/qsd2_w1 -store True
echo "---> 2D_histo, CieLAB, CH 1 & 2"
python m1_w2.py -t 1 -d 2D_hist -c CieLAB -ch1 1 -ch2 2 -lvl 1 -src ../../Datasets/qsd2_w1 -store True

echo "---> 2D_histo, YCbCr, CH 0 & 1"
python m1_w2.py -t 1 -d 2D_hist -c YCbCr -ch1 0 -ch2 1 -lvl 1 -src ../../Datasets/qsd2_w1 -store True
echo "---> 2D_histo, YCbCr, CH 0 & 2"
python m1_w2.py -t 1 -d 2D_hist -c YCbCr -ch1 0 -ch2 2 -lvl 1 -src ../../Datasets/qsd2_w1 -store True
echo "---> 2D_histo, YCbCr, CH 1 & 2"
python m1_w2.py -t 1 -d 2D_hist -c YCbCr -ch1 1 -ch2 2 -lvl 1 -src ../../Datasets/qsd2_w1 -store True

echo "---> 3D_histo, RGB"
python m1_w2.py -t 1 -d 3D_hist -c RGB -lvl 1 -src ../../Datasets/qsd2_w1 -store True
echo "---> 3D_histo, HSV"
python m1_w2.py -t 1 -d 3D_hist -c HSV -lvl 1 -src ../../Datasets/qsd2_w1 -store True
echo "---> 3D_histo, CieLAB"
python m1_w2.py -t 1 -d 3D_hist -c CieLAB -lvl 1 -src ../../Datasets/qsd2_w1 -store True
echo "---> 3D_histo, YCbCr"
python m1_w2.py -t 1 -d 3D_hist -c YCbCr -lvl 1 -src ../../Datasets/qsd2_w1 -store True



echo "------------ Level 3 -----------"
echo "---> 1D_histo"
python m1_w2.py -t 1 -d 1D_hist -lvl 2 -src ../../Datasets/qsd2_w1 -store True

echo "---> 2D_histo, RGB, CH 0 & 1"
python m1_w2.py -t 1 -d 2D_hist -c RGB -ch1 0 -ch2 1 -lvl 2 -src ../../Datasets/qsd2_w1 -store True
echo "---> 2D_histo, RGB, CH 0 & 2"
python m1_w2.py -t 1 -d 2D_hist -c RGB -ch1 0 -ch2 2 -lvl 2 -src ../../Datasets/qsd2_w1 -store True
echo "---> 2D_histo, RGB, CH 1 & 2"
python m1_w2.py -t 1 -d 2D_hist -c RGB -ch1 1 -ch2 2 -lvl 2 -src ../../Datasets/qsd2_w1 -store True

echo "---> 2D_histo, HSV, CH 0 & 1"
python m1_w2.py -t 1 -d 2D_hist -c HSV -ch1 0 -ch2 1 -lvl 2 -src ../../Datasets/qsd2_w1 -store True
echo "---> 2D_histo, HSV, CH 0 & 2"
python m1_w2.py -t 1 -d 2D_hist -c HSV -ch1 0 -ch2 2 -lvl 2 -src ../../Datasets/qsd2_w1 -store True
echo "---> 2D_histo, HSV, CH 1 & 2"
python m1_w2.py -t 1 -d 2D_hist -c HSV -ch1 1 -ch2 2 -lvl 2 -src ../../Datasets/qsd2_w1 -store True

echo "---> 2D_histo, CieLAB, CH 0 & 1"
python m1_w2.py -t 1 -d 2D_hist -c CieLAB -ch1 0 -ch2 1 -lvl 2 -src ../../Datasets/qsd2_w1 -store True
echo "---> 2D_histo, CieLAB, CH 0 & 2"
python m1_w2.py -t 1 -d 2D_hist -c CieLAB -ch1 0 -ch2 2 -lvl 2 -src ../../Datasets/qsd2_w1 -store True
echo "---> 2D_histo, CieLAB, CH 1 & 2"
python m1_w2.py -t 1 -d 2D_hist -c CieLAB -ch1 1 -ch2 2 -lvl 2 -src ../../Datasets/qsd2_w1 -store True

echo "---> 2D_histo, YCbCr, CH 0 & 1"
python m1_w2.py -t 1 -d 2D_hist -c YCbCr -ch1 0 -ch2 1 -lvl 2 -src ../../Datasets/qsd2_w1 -store True
echo "---> 2D_histo, YCbCr, CH 0 & 2"
python m1_w2.py -t 1 -d 2D_hist -c YCbCr -ch1 0 -ch2 2 -lvl 2 -src ../../Datasets/qsd2_w1 -store True
echo "---> 2D_histo, YCbCr, CH 1 & 2"
python m1_w2.py -t 1 -d 2D_hist -c YCbCr -ch1 1 -ch2 2 -lvl 2 -src ../../Datasets/qsd2_w1 -store True

echo "---> 3D_histo, RGB"
python m1_w2.py -t 1 -d 3D_hist -c RGB -lvl 2 -src ../../Datasets/qsd2_w1 -store True
echo "---> 3D_histo, HSV"
python m1_w2.py -t 1 -d 3D_hist -c HSV -lvl 2 -src ../../Datasets/qsd2_w1 -store True
echo "---> 3D_histo, CieLAB"
python m1_w2.py -t 1 -d 3D_hist -c CieLAB -lvl 2 -src ../../Datasets/qsd2_w1 -store True
echo "---> 3D_histo, YCbCr"
python m1_w2.py -t 1 -d 3D_hist -c YCbCr -lvl 2 -src ../../Datasets/qsd2_w1 -store True



echo "------------ Level 3 -----------"
echo "---> 1D_histo"
python m1_w2.py -t 1 -d 1D_hist -lvl 3 -src ../../Datasets/qsd2_w1 -store True

echo "---> 2D_histo, RGB, CH 0 & 1"
python m1_w2.py -t 1 -d 2D_hist -c RGB -ch1 0 -ch2 1 -lvl 3 -src ../../Datasets/qsd2_w1 -store True
echo "---> 2D_histo, RGB, CH 0 & 2"
python m1_w2.py -t 1 -d 2D_hist -c RGB -ch1 0 -ch2 2 -lvl 3 -src ../../Datasets/qsd2_w1 -store True
echo "---> 2D_histo, RGB, CH 1 & 2"
python m1_w2.py -t 1 -d 2D_hist -c RGB -ch1 1 -ch2 2 -lvl 3 -src ../../Datasets/qsd2_w1 -store True

echo "---> 2D_histo, HSV, CH 0 & 1"
python m1_w2.py -t 1 -d 2D_hist -c HSV -ch1 0 -ch2 1 -lvl 3 -src ../../Datasets/qsd2_w1 -store True
echo "---> 2D_histo, HSV, CH 0 & 2"
python m1_w2.py -t 1 -d 2D_hist -c HSV -ch1 0 -ch2 2 -lvl 3 -src ../../Datasets/qsd2_w1 -store True
echo "---> 2D_histo, HSV, CH 1 & 2"
python m1_w2.py -t 1 -d 2D_hist -c HSV -ch1 1 -ch2 2 -lvl 3 -src ../../Datasets/qsd2_w1 -store True

echo "---> 2D_histo, CieLAB, CH 0 & 1"
python m1_w2.py -t 1 -d 2D_hist -c CieLAB -ch1 0 -ch2 1 -lvl 3 -src ../../Datasets/qsd2_w1 -store True
echo "---> 2D_histo, CieLAB, CH 0 & 2"
python m1_w2.py -t 1 -d 2D_hist -c CieLAB -ch1 0 -ch2 2 -lvl 3 -src ../../Datasets/qsd2_w1 -store True
echo "---> 2D_histo, CieLAB, CH 1 & 2"
python m1_w2.py -t 1 -d 2D_hist -c CieLAB -ch1 1 -ch2 2 -lvl 3 -src ../../Datasets/qsd2_w1 -store True

echo "---> 2D_histo, YCbCr, CH 0 & 1"
python m1_w2.py -t 1 -d 2D_hist -c YCbCr -ch1 0 -ch2 1 -lvl 3 -src ../../Datasets/qsd2_w1 -store True
echo "---> 2D_histo, YCbCr, CH 0 & 2"
python m1_w2.py -t 1 -d 2D_hist -c YCbCr -ch1 0 -ch2 2 -lvl 3 -src ../../Datasets/qsd2_w1 -store True
echo "---> 2D_histo, YCbCr, CH 1 & 2"
python m1_w2.py -t 1 -d 2D_hist -c YCbCr -ch1 1 -ch2 2 -lvl 3 -src ../../Datasets/qsd2_w1 -store True

echo "---> 3D_histo, RGB"
python m1_w2.py -t 1 -d 3D_hist -c RGB -lvl 3 -src ../../Datasets/qsd2_w1 -store True
echo "---> 3D_histo, HSV"
python m1_w2.py -t 1 -d 3D_hist -c HSV -lvl 3 -src ../../Datasets/qsd2_w1 -store True
echo "---> 3D_histo, CieLAB"
python m1_w2.py -t 1 -d 3D_hist -c CieLAB -lvl 3 -src ../../Datasets/qsd2_w1 -store True
echo "---> 3D_histo, YCbCr"
python m1_w2.py -t 1 -d 3D_hist -c YCbCr -lvl 3 -src ../../Datasets/qsd2_w1 -store True