#!/bin/bash
'
echo "--------- TASK 1 TESTS ---------"
echo "------------ Level 1 -----------"
echo "---> 1D_histo"
python m1_w2.py -t 1 -d 1D_hist -lvl 1 -src ../../Datasets/qsd2_w1 -store True

echo "---> 2D_histo, RGB, CH 0 & 1"
python m1_w2.py -t 1 -d 2D_hist -c RGB -ch1 0 -ch2 1 -lvl 1 -src ../../Datasets/qsd2_w1 -store True
echo "---> 2D_histo, RGB, CH 0 & 2"
python m1_w2.py -t 1 -d 2D_hist -c RGB -ch1 0 -ch2 2 -lvl 1 -src ../../Datasets/qsd2_w1 -store True
echo "---> 2D_histo, RGB, CH 1 & 2"
python m1_w2.py -t 1 -d 2D_hist -c RGB -ch1 1 -ch2 2 -lvl 1 -src ../../Datasets/qsd2_w1 -store True

echo "---> 2D_histo, HSV, CH 0 & 1"
python m1_w2.py -t 1 -d 2D_hist -c HSV -ch1 0 -ch2 1 -lvl 1 -src ../../Datasets/qsd2_w1 -store True
echo "---> 2D_histo, HSV, CH 0 & 2"
python m1_w2.py -t 1 -d 2D_hist -c HSV -ch1 0 -ch2 2 -lvl 1 -src ../../Datasets/qsd2_w1 -store True
echo "---> 2D_histo, HSV, CH 1 & 2"
python m1_w2.py -t 1 -d 2D_hist -c HSV -ch1 1 -ch2 2 -lvl 1 -src ../../Datasets/qsd2_w1 -store True

echo "---> 2D_histo, CieLAB, CH 0 & 1"
python m1_w2.py -t 1 -d 2D_hist -c CieLAB -ch1 0 -ch2 1 -lvl 1 -src ../../Datasets/qsd2_w1 -store True
echo "---> 2D_histo, CieLAB, CH 0 & 2"
python m1_w2.py -t 1 -d 2D_hist -c CieLAB -ch1 0 -ch2 2 -lvl 1 -src ../../Datasets/qsd2_w1 -store True
echo "---> 2D_histo, CieLAB, CH 1 & 2"
python m1_w2.py -t 1 -d 2D_hist -c CieLAB -ch1 1 -ch2 2 -lvl 1 -src ../../Datasets/qsd2_w1 -store True

echo "---> 2D_histo, YCbCr, CH 0 & 1"
python m1_w2.py -t 1 -d 2D_hist -c YCbCr -ch1 0 -ch2 1 -lvl 1 -src ../../Datasets/qsd2_w1 -store True
echo "---> 2D_histo, YCbCr, CH 0 & 2"
python m1_w2.py -t 1 -d 2D_hist -c YCbCr -ch1 0 -ch2 2 -lvl 1 -src ../../Datasets/qsd2_w1 -store True
echo "---> 2D_histo, YCbCr, CH 1 & 2"
python m1_w2.py -t 1 -d 2D_hist -c YCbCr -ch1 1 -ch2 2 -lvl 1 -src ../../Datasets/qsd2_w1 -store True

echo "---> 3D_histo, RGB"
python m1_w2.py -t 1 -d 3D_hist -c RGB -lvl 1 -src ../../Datasets/qsd2_w1 -store True
echo "---> 3D_histo, HSV"
python m1_w2.py -t 1 -d 3D_hist -c HSV -lvl 1 -src ../../Datasets/qsd2_w1 -store True
echo "---> 3D_histo, CieLAB"
python m1_w2.py -t 1 -d 3D_hist -c CieLAB -lvl 1 -src ../../Datasets/qsd2_w1 -store True
echo "---> 3D_histo, YCbCr"
python m1_w2.py -t 1 -d 3D_hist -c YCbCr -lvl 1 -src ../../Datasets/qsd2_w1 -store True



echo "------------ Level 3 -----------"
echo "---> 1D_histo"
python m1_w2.py -t 1 -d 1D_hist -lvl 2 -src ../../Datasets/qsd2_w1 -store True

echo "---> 2D_histo, RGB, CH 0 & 1"
python m1_w2.py -t 1 -d 2D_hist -c RGB -ch1 0 -ch2 1 -lvl 2 -src ../../Datasets/qsd2_w1 -store True
echo "---> 2D_histo, RGB, CH 0 & 2"
python m1_w2.py -t 1 -d 2D_hist -c RGB -ch1 0 -ch2 2 -lvl 2 -src ../../Datasets/qsd2_w1 -store True
echo "---> 2D_histo, RGB, CH 1 & 2"
python m1_w2.py -t 1 -d 2D_hist -c RGB -ch1 1 -ch2 2 -lvl 2 -src ../../Datasets/qsd2_w1 -store True

echo "---> 2D_histo, HSV, CH 0 & 1"
python m1_w2.py -t 1 -d 2D_hist -c HSV -ch1 0 -ch2 1 -lvl 2 -src ../../Datasets/qsd2_w1 -store True
echo "---> 2D_histo, HSV, CH 0 & 2"
python m1_w2.py -t 1 -d 2D_hist -c HSV -ch1 0 -ch2 2 -lvl 2 -src ../../Datasets/qsd2_w1 -store True
echo "---> 2D_histo, HSV, CH 1 & 2"
python m1_w2.py -t 1 -d 2D_hist -c HSV -ch1 1 -ch2 2 -lvl 2 -src ../../Datasets/qsd2_w1 -store True

echo "---> 2D_histo, CieLAB, CH 0 & 1"
python m1_w2.py -t 1 -d 2D_hist -c CieLAB -ch1 0 -ch2 1 -lvl 2 -src ../../Datasets/qsd2_w1 -store True
echo "---> 2D_histo, CieLAB, CH 0 & 2"
python m1_w2.py -t 1 -d 2D_hist -c CieLAB -ch1 0 -ch2 2 -lvl 2 -src ../../Datasets/qsd2_w1 -store True
echo "---> 2D_histo, CieLAB, CH 1 & 2"
python m1_w2.py -t 1 -d 2D_hist -c CieLAB -ch1 1 -ch2 2 -lvl 2 -src ../../Datasets/qsd2_w1 -store True

echo "---> 2D_histo, YCbCr, CH 0 & 1"
python m1_w2.py -t 1 -d 2D_hist -c YCbCr -ch1 0 -ch2 1 -lvl 2 -src ../../Datasets/qsd2_w1 -store True
echo "---> 2D_histo, YCbCr, CH 0 & 2"
python m1_w2.py -t 1 -d 2D_hist -c YCbCr -ch1 0 -ch2 2 -lvl 2 -src ../../Datasets/qsd2_w1 -store True
echo "---> 2D_histo, YCbCr, CH 1 & 2"
python m1_w2.py -t 1 -d 2D_hist -c YCbCr -ch1 1 -ch2 2 -lvl 2 -src ../../Datasets/qsd2_w1 -store True

echo "---> 3D_histo, RGB"
python m1_w2.py -t 1 -d 3D_hist -c RGB -lvl 2 -src ../../Datasets/qsd2_w1 -store True
echo "---> 3D_histo, HSV"
python m1_w2.py -t 1 -d 3D_hist -c HSV -lvl 2 -src ../../Datasets/qsd2_w1 -store True
echo "---> 3D_histo, CieLAB"
python m1_w2.py -t 1 -d 3D_hist -c CieLAB -lvl 2 -src ../../Datasets/qsd2_w1 -store True
echo "---> 3D_histo, YCbCr"
python m1_w2.py -t 1 -d 3D_hist -c YCbCr -lvl 2 -src ../../Datasets/qsd2_w1 -store True



echo "------------ Level 3 -----------"
echo "---> 1D_histo"
python m1_w2.py -t 1 -d 1D_hist -lvl 3 -src ../../Datasets/qsd2_w1 -store True

echo "---> 2D_histo, RGB, CH 0 & 1"
python m1_w2.py -t 1 -d 2D_hist -c RGB -ch1 0 -ch2 1 -lvl 3 -src ../../Datasets/qsd2_w1 -store True
echo "---> 2D_histo, RGB, CH 0 & 2"
python m1_w2.py -t 1 -d 2D_hist -c RGB -ch1 0 -ch2 2 -lvl 3 -src ../../Datasets/qsd2_w1 -store True
echo "---> 2D_histo, RGB, CH 1 & 2"
python m1_w2.py -t 1 -d 2D_hist -c RGB -ch1 1 -ch2 2 -lvl 3 -src ../../Datasets/qsd2_w1 -store True

echo "---> 2D_histo, HSV, CH 0 & 1"
python m1_w2.py -t 1 -d 2D_hist -c HSV -ch1 0 -ch2 1 -lvl 3 -src ../../Datasets/qsd2_w1 -store True
echo "---> 2D_histo, HSV, CH 0 & 2"
python m1_w2.py -t 1 -d 2D_hist -c HSV -ch1 0 -ch2 2 -lvl 3 -src ../../Datasets/qsd2_w1 -store True
echo "---> 2D_histo, HSV, CH 1 & 2"
python m1_w2.py -t 1 -d 2D_hist -c HSV -ch1 1 -ch2 2 -lvl 3 -src ../../Datasets/qsd2_w1 -store True

echo "---> 2D_histo, CieLAB, CH 0 & 1"
python m1_w2.py -t 1 -d 2D_hist -c CieLAB -ch1 0 -ch2 1 -lvl 3 -src ../../Datasets/qsd2_w1 -store True
echo "---> 2D_histo, CieLAB, CH 0 & 2"
python m1_w2.py -t 1 -d 2D_hist -c CieLAB -ch1 0 -ch2 2 -lvl 3 -src ../../Datasets/qsd2_w1 -store True
echo "---> 2D_histo, CieLAB, CH 1 & 2"
python m1_w2.py -t 1 -d 2D_hist -c CieLAB -ch1 1 -ch2 2 -lvl 3 -src ../../Datasets/qsd2_w1 -store True

echo "---> 2D_histo, YCbCr, CH 0 & 1"
python m1_w2.py -t 1 -d 2D_hist -c YCbCr -ch1 0 -ch2 1 -lvl 3 -src ../../Datasets/qsd2_w1 -store True
echo "---> 2D_histo, YCbCr, CH 0 & 2"
python m1_w2.py -t 1 -d 2D_hist -c YCbCr -ch1 0 -ch2 2 -lvl 3 -src ../../Datasets/qsd2_w1 -store True
echo "---> 2D_histo, YCbCr, CH 1 & 2"
python m1_w2.py -t 1 -d 2D_hist -c YCbCr -ch1 1 -ch2 2 -lvl 3 -src ../../Datasets/qsd2_w1 -store True

echo "---> 3D_histo, RGB"
python m1_w2.py -t 1 -d 3D_hist -c RGB -lvl 3 -src ../../Datasets/qsd2_w1 -store True
echo "---> 3D_histo, HSV"
python m1_w2.py -t 1 -d 3D_hist -c HSV -lvl 3 -src ../../Datasets/qsd2_w1 -store True
echo "---> 3D_histo, CieLAB"
python m1_w2.py -t 1 -d 3D_hist -c CieLAB -lvl 3 -src ../../Datasets/qsd2_w1 -store True
echo "---> 3D_histo, YCbCr"
python m1_w2.py -t 1 -d 3D_hist -c YCbCr -lvl 3 -src ../../Datasets/qsd2_w1 -store True


echo "----- T2 - Retrieval eval qsd2_w1"
echo "---> msc, lvl 1, l1, 3d rgb"
python m1_w2.py -t 2 -bm msc -m l1 -src ../../Datasets/qsd2_w1/ -bbdd ../../Datasets/BBDD/ -d "3D_hist" -c "RGB" -store True -lvl 1
echo "---> msc, lvl 2, l1, 3d rgb"
python m1_w2.py -t 2 -bm msc -m l1 -src ../../Datasets/qsd2_w1/ -bbdd ../../Datasets/BBDD/ -d "3D_hist" -c "RGB" -store True -lvl 2
echo "---> msc, lvl 3, l1, 3d rgb"
python m1_w2.py -t 2 -bm msc -m l1 -src ../../Datasets/qsd2_w1/ -bbdd ../../Datasets/BBDD/ -d "3D_hist" -c "RGB" -store True -lvl 3

echo "---> msc, lvl 1, x2, 3d rgb"
python m1_w2.py -t 2 -bm msc -m x2 -src ../../Datasets/qsd2_w1/ -bbdd ../../Datasets/BBDD/ -d "3D_hist" -c "RGB" -store True -lvl 1
echo "---> msc, lvl 2, x2, 3d rgb"
python m1_w2.py -t 2 -bm msc -m x2 -src ../../Datasets/qsd2_w1/ -bbdd ../../Datasets/BBDD/ -d "3D_hist" -c "RGB" -store True -lvl 2
echo "---> msc, lvl 3, x2, 3d rgb"
python m1_w2.py -t 2 -bm msc -m x2 -src ../../Datasets/qsd2_w1/ -bbdd ../../Datasets/BBDD/ -d "3D_hist" -c "RGB" -store True -lvl 3

echo "---> msc, lvl 1, l1, 3d hsv"
python m1_w2.py -t 2 -bm msc -m l1 -src ../../Datasets/qsd2_w1/ -bbdd ../../Datasets/BBDD/ -d "3D_hist" -c "HSV" -store True -lvl 1
echo "---> msc, lvl 2, l1, 3d hsv"
python m1_w2.py -t 2 -bm msc -m l1 -src ../../Datasets/qsd2_w1/ -bbdd ../../Datasets/BBDD/ -d "3D_hist" -c "HSV" -store True -lvl 2
echo "---> msc, lvl 3, l1, 3d hsv"
python m1_w2.py -t 2 -bm msc -m l1 -src ../../Datasets/qsd2_w1/ -bbdd ../../Datasets/BBDD/ -d "3D_hist" -c "HSV" -store True -lvl 3

echo "---> msc, lvl 1, x2, 3d hsv"
python m1_w2.py -t 2 -bm msc -m x2 -src ../../Datasets/qsd2_w1/ -bbdd ../../Datasets/BBDD/ -d "3D_hist" -c "HSV" -store True -lvl 1
echo "---> msc, lvl 2, x2, 3d hsv"
python m1_w2.py -t 2 -bm msc -m x2 -src ../../Datasets/qsd2_w1/ -bbdd ../../Datasets/BBDD/ -d "3D_hist" -c "HSV" -store True -lvl 2
echo "---> msc, lvl 3, x2, 3d hsv"
python m1_w2.py -t 2 -bm msc -m x2 -src ../../Datasets/qsd2_w1/ -bbdd ../../Datasets/BBDD/ -d "3D_hist" -c "HSV" -store True -lvl 3

echo "---> msc, lvl 1, l1, 2d hsv"
python m1_w2.py -t 2 -bm msc -m l1 -src ../../Datasets/qsd2_w1/ -bbdd ../../Datasets/BBDD/ -d "2D_hist" -ch1 0 -ch2 1 -c "HSV" -store True -lvl 1
echo "---> msc, lvl 2, l1, 2d hsv"
python m1_w2.py -t 2 -bm msc -m l1 -src ../../Datasets/qsd2_w1/ -bbdd ../../Datasets/BBDD/ -d "2D_hist" -ch1 0 -ch2 1 -c "HSV" -store True -lvl 2
echo "---> msc, lvl 3, l1, 2d hsv"
python m1_w2.py -t 2 -bm msc -m l1 -src ../../Datasets/qsd2_w1/ -bbdd ../../Datasets/BBDD/ -d "2D_hist" -ch1 0 -ch2 1 -c "HSV" -store True -lvl 3

echo "---> msc, lvl 1, x2, 2d hsv"
python m1_w2.py -t 2 -bm msc -m x2 -src ../../Datasets/qsd2_w1/ -bbdd ../../Datasets/BBDD/ -d "2D_hist" -ch1 0 -ch2 1 -c "HSV" -store True -lvl 1
echo "---> msc, lvl 2, x2, 2d hsv"
python m1_w2.py -t 2 -bm msc -m x2 -src ../../Datasets/qsd2_w1/ -bbdd ../../Datasets/BBDD/ -d "2D_hist" -ch1 0 -ch2 1 -c "HSV" -store True -lvl 2
echo "---> msc, lvl 3, x2, 2d hsv"
python m1_w2.py -t 2 -bm msc -m x2 -src ../../Datasets/qsd2_w1/ -bbdd ../../Datasets/BBDD/ -d "2D_hist" -ch1 0 -ch2 1 -c "HSV" -store True -lvl 3

echo "---> canny, lvl 1, l1, 3d rgb"
python m1_w2.py -t 2 -bm canny -m l1 -src ../../Datasets/qsd2_w1/ -bbdd ../../Datasets/BBDD/ -d "3D_hist" -c "RGB" -store True -lvl 1
echo "---> canny, lvl 2, l1, 3d rgb"
python m1_w2.py -t 2 -bm canny -m l1 -src ../../Datasets/qsd2_w1/ -bbdd ../../Datasets/BBDD/ -d "3D_hist" -c "RGB" -store True -lvl 2
echo "---> canny, lvl 3, l1, 3d rgb"
python m1_w2.py -t 2 -bm canny -m l1 -src ../../Datasets/qsd2_w1/ -bbdd ../../Datasets/BBDD/ -d "3D_hist" -c "RGB" -store True -lvl 3

echo "---> canny, lvl 1, x2, 3d rgb"
python m1_w2.py -t 2 -bm canny -m x2 -src ../../Datasets/qsd2_w1/ -bbdd ../../Datasets/BBDD/ -d "3D_hist" -c "RGB" -store True -lvl 1
echo "---> canny, lvl 2, x2, 3d rgb"
python m1_w2.py -t 2 -bm canny -m x2 -src ../../Datasets/qsd2_w1/ -bbdd ../../Datasets/BBDD/ -d "3D_hist" -c "RGB" -store True -lvl 2
echo "---> canny, lvl 3, x2, 3d rgb"
python m1_w2.py -t 2 -bm canny -m x2 -src ../../Datasets/qsd2_w1/ -bbdd ../../Datasets/BBDD/ -d "3D_hist" -c "RGB" -store True -lvl 3

echo "---> canny, lvl 1, l1, 3d hsv"
python m1_w2.py -t 2 -bm canny -m l1 -src ../../Datasets/qsd2_w1/ -bbdd ../../Datasets/BBDD/ -d "3D_hist" -c "HSV" -store True -lvl 1
echo "---> canny, lvl 2, l1, 3d hsv"
python m1_w2.py -t 2 -bm canny -m l1 -src ../../Datasets/qsd2_w1/ -bbdd ../../Datasets/BBDD/ -d "3D_hist" -c "HSV" -store True -lvl 2
echo "---> canny, lvl 3, l1, 3d hsv"
python m1_w2.py -t 2 -bm canny -m l1 -src ../../Datasets/qsd2_w1/ -bbdd ../../Datasets/BBDD/ -d "3D_hist" -c "HSV" -store True -lvl 3

echo "---> canny, lvl 1, x2, 3d hsv"
python m1_w2.py -t 2 -bm canny -m x2 -src ../../Datasets/qsd2_w1/ -bbdd ../../Datasets/BBDD/ -d "3D_hist" -c "HSV" -store True -lvl 1
echo "---> canny, lvl 2, x2, 3d hsv"
python m1_w2.py -t 2 -bm canny -m x2 -src ../../Datasets/qsd2_w1/ -bbdd ../../Datasets/BBDD/ -d "3D_hist" -c "HSV" -store True -lvl 2
echo "---> canny, lvl 3, x2, 3d hsv"
python m1_w2.py -t 2 -bm canny -m x2 -src ../../Datasets/qsd2_w1/ -bbdd ../../Datasets/BBDD/ -d "3D_hist" -c "HSV" -store True -lvl 3

echo "---> canny, lvl 1, l1, 2d hsv"
python m1_w2.py -t 2 -bm canny -m l1 -src ../../Datasets/qsd2_w1/ -bbdd ../../Datasets/BBDD/ -d "2D_hist" -ch1 0 -ch2 1 -c "HSV" -store True -lvl 1
echo "---> canny, lvl 2, l1, 2d hsv"
python m1_w2.py -t 2 -bm canny -m l1 -src ../../Datasets/qsd2_w1/ -bbdd ../../Datasets/BBDD/ -d "2D_hist" -ch1 0 -ch2 1 -c "HSV" -store True -lvl 2
echo "---> canny, lvl 3, l1, 2d hsv"
python m1_w2.py -t 2 -bm canny -m l1 -src ../../Datasets/qsd2_w1/ -bbdd ../../Datasets/BBDD/ -d "2D_hist" -ch1 0 -ch2 1 -c "HSV" -store True -lvl 3

echo "---> canny, lvl 1, x2, 2d hsv"
python m1_w2.py -t 2 -bm canny -m x2 -src ../../Datasets/qsd2_w1/ -bbdd ../../Datasets/BBDD/ -d "2D_hist" -ch1 0 -ch2 1 -c "HSV" -store True -lvl 1
echo "---> canny, lvl 2, x2, 2d hsv"
python m1_w2.py -t 2 -bm canny -m x2 -src ../../Datasets/qsd2_w1/ -bbdd ../../Datasets/BBDD/ -d "2D_hist" -ch1 0 -ch2 1 -c "HSV" -store True -lvl 2
echo "---> canny, lvl 3, x2, 2d hsv"
python m1_w2.py -t 2 -bm canny -m x2 -src ../../Datasets/qsd2_w1/ -bbdd ../../Datasets/BBDD/ -d "2D_hist" -ch1 0 -ch2 1 -c "HSV" -store True -lvl 3
'''
'''
echo "----- T6 - BKGD -----"
echo "---> msc"
python m1_w2.py -t 6 -bm msc -src ../../Datasets/qsd2_w1 -store True
echo "---> mcst RGB"
python m1_w2.py -t 6 -bm msc -c RGB -src ../../Datasets/qsd2_w1 -store True
echo "---> mcst HSV"
python m1_w2.py -t 6 -bm msc -c HSV -src ../../Datasets/qsd2_w1 -store True
echo "---> mcck RGB"
python m1_w2.py -t 6 -bm mcck -c RGB -src ../../Datasets/qsd2_w1 -store True
echo "---> mcck HSV"
python m1_w2.py -t 6 -bm mcck -c HSV -src ../../Datasets/qsd2_w1 -store True
echo "---> canny"
python m1_w2.py -t 6 -bm canny -src ../../Datasets/qsd2_w1 -store True
echo "---> watershed"
python m1_w2.py -t 6 -bm watershed -src ../../Datasets/qsd2_w1 -store True
'''
'''
echo "QSD1"
python m1_w2.py -t 3  -m l1 -src ../../Datasets/qsd1_w2/ -bbdd ../../Datasets/BBDD/ -lvl 1 -k 10
python m1_w2.py -t 3  -m l1 -src ../../Datasets/qsd1_w2/ -bbdd ../../Datasets/BBDD/ -lvl 2 -k 10
python m1_w2.py -t 3  -m l1 -src ../../Datasets/qsd1_w2/ -bbdd ../../Datasets/BBDD/ -lvl 3 -k 10

python m1_w2.py -t 3  -m l1 -src ../../Datasets/qsd1_w2/ -bbdd ../../Datasets/BBDD/ -lvl 1 -k 5
python m1_w2.py -t 3  -m l1 -src ../../Datasets/qsd1_w2/ -bbdd ../../Datasets/BBDD/ -lvl 2 -k 5
python m1_w2.py -t 3  -m l1 -src ../../Datasets/qsd1_w2/ -bbdd ../../Datasets/BBDD/ -lvl 3 -k 5

python m1_w2.py -t 3  -m l1 -src ../../Datasets/qsd1_w2/ -bbdd ../../Datasets/BBDD/ -lvl 1 -k 3
python m1_w2.py -t 3  -m l1 -src ../../Datasets/qsd1_w2/ -bbdd ../../Datasets/BBDD/ -lvl 2 -k 3
python m1_w2.py -t 3  -m l1 -src ../../Datasets/qsd1_w2/ -bbdd ../../Datasets/BBDD/ -lvl 3 -k 3
'''
echo "QSD2"
python m1_w2.py -t 3  -m l1 -src ../../Datasets/qsd2_w2/ -bbdd ../../Datasets/BBDD/ -lvl 1 -k 10
python m1_w2.py -t 3  -m l1 -src ../../Datasets/qsd2_w2/ -bbdd ../../Datasets/BBDD/ -lvl 2 -k 10
python m1_w2.py -t 3  -m l1 -src ../../Datasets/qsd2_w2/ -bbdd ../../Datasets/BBDD/ -lvl 3 -k 10

python m1_w2.py -t 3  -m l1 -src ../../Datasets/qsd2_w2/ -bbdd ../../Datasets/BBDD/ -lvl 1 -k 5
python m1_w2.py -t 3  -m l1 -src ../../Datasets/qsd2_w2/ -bbdd ../../Datasets/BBDD/ -lvl 2 -k 5
python m1_w2.py -t 3  -m l1 -src ../../Datasets/qsd2_w2/ -bbdd ../../Datasets/BBDD/ -lvl 3 -k 5

python m1_w2.py -t 3  -m l1 -src ../../Datasets/qsd2_w2/ -bbdd ../../Datasets/BBDD/ -lvl 1 -k 3
python m1_w2.py -t 3  -m l1 -src ../../Datasets/qsd2_w2/ -bbdd ../../Datasets/BBDD/ -lvl 2 -k 3
python m1_w2.py -t 3  -m l1 -src ../../Datasets/qsd2_w2/ -bbdd ../../Datasets/BBDD/ -lvl 3 -k 3